import { Timestamp } from 'firebase/firestore';

export interface StockSnapshot {
  id?: string;
  companyId: string;
  snapshotDate: Timestamp | Date;
  
  // Array of all products and their stock at this point in time
  products: {
    productId: string;
    quantity: number;
    averageCost: number;
    valuation: number; // quantity * averageCost
  }[];
  
  totalValuation: number; // Sum of all valuations
  totalProducts: number;
  
  createdBy: string;
  createdAt: Timestamp | Date;
  isAutomatic: boolean; // True if generated by a background job
}
